services:
  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:latest
    container_name: portfolio-frontend
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
