import {
  PlanningTemplate,
  PaymentFrequency,
  PaymentType,
  RiskTolerance,
  CalculatedVariableType,
  TemplateCategory,
} from '../types/financialFreedom.types';

export const FINANCIAL_FREEDOM_TEMPLATES: PlanningTemplate[] = [
  {
    id: 'savings-investment',
    name: 'Tiết kiệm và đầu tư',
    nameEn: 'Savings & Investment',
    description: 'Dành cho người đang làm việc, muốn tích lũy và đầu tư để đạt mục tiêu tài chính trong tương lai.',
    descriptionEn: 'For working individuals who want to save and invest to achieve financial goals in the future.',
    icon: 'savings',
    category: TemplateCategory.SAVINGS,
    defaults: {
      targetMethod: 'fromExpenses',
      monthlyExpenses: 30000000,
      withdrawalRate: 0.05,
      initialInvestment: 500000000,
      periodicPayment: 10000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: 15,
      expectedReturnRate: undefined,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.MODERATE,
    },
    calculateVariable: CalculatedVariableType.RETURN_RATE,
    guidance: 'Template này phù hợp cho người đang làm việc, có thu nhập ổn định, muốn tích lũy để tự do tài chính.',
    guidanceEn: 'This template is suitable for working individuals with stable income who want to accumulate wealth for financial freedom.',
    tips: [
      'Điều chỉnh chi phí sinh hoạt theo tình hình thực tế của bạn',
      'Tăng tiền bổ sung hàng tháng sẽ giảm tỉ suất lợi nhuận yêu cầu',
      'Có thể kéo dài thời gian đầu tư để giảm áp lực về lợi nhuận',
    ],
    tipsEn: [
      'Adjust monthly expenses according to your actual situation',
      'Increasing monthly contributions will reduce required return rate',
      'You can extend investment period to reduce return rate pressure',
    ],
  },
  {
    id: 'retirement-withdrawal',
    name: 'Đã nghỉ hưu, rút tiền',
    nameEn: 'Retirement Withdrawal',
    description: 'Dành cho người đã nghỉ hưu, có khoản tiết kiệm và muốn rút tiền định kỳ để chi tiêu.',
    descriptionEn: 'For retired individuals who have savings and want to withdraw money periodically for expenses.',
    icon: 'retirement',
    category: TemplateCategory.RETIREMENT,
    defaults: {
      targetMethod: 'fromExpenses',
      monthlyExpenses: 30000000,
      withdrawalRate: 0.05,
      initialInvestment: 1000000000,
      periodicPayment: undefined,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.WITHDRAWAL,
      investmentYears: 20,
      expectedReturnRate: undefined,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.CONSERVATIVE,
    },
    calculateVariable: CalculatedVariableType.RETURN_RATE,
    guidance: 'Template này phù hợp cho người đã nghỉ hưu, cần rút tiền hàng tháng để chi tiêu.',
    guidanceEn: 'This template is suitable for retired individuals who need to withdraw money monthly for expenses.',
    tips: [
      'Tỷ lệ rút 4% là an toàn cho hầu hết trường hợp',
      'Nên đầu tư an toàn để bảo toàn vốn',
      'Theo dõi portfolio thường xuyên để đảm bảo không cạn kiệt',
    ],
    tipsEn: [
      '4% withdrawal rate is safe for most cases',
      'Invest conservatively to preserve capital',
      'Monitor portfolio regularly to ensure it doesn\'t deplete',
    ],
  },
  {
    id: 'early-retirement',
    name: 'Tự do tài chính sớm',
    nameEn: 'Early Retirement (FIRE)',
    description: 'Dành cho người muốn nghỉ hưu sớm (trước 50 tuổi), cần tích lũy nhanh để đạt tự do tài chính.',
    descriptionEn: 'For individuals who want to retire early (before 50), need to accumulate quickly for financial freedom.',
    icon: 'fire',
    category: TemplateCategory.RETIREMENT,
    defaults: {
      targetMethod: 'fromExpenses',
      monthlyExpenses: 40000000,
      withdrawalRate: 0.05,
      initialInvestment: 1000000000,
      periodicPayment: 20000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: undefined,
      expectedReturnRate: 12,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.AGGRESSIVE,
    },
    calculateVariable: CalculatedVariableType.YEARS,
    guidance: 'Template này phù hợp cho người muốn nghỉ hưu sớm, sẵn sàng đầu tư mạnh và chấp nhận rủi ro cao.',
    guidanceEn: 'This template is suitable for early retirement seekers who are willing to invest aggressively and accept higher risk.',
    tips: [
      'FIRE yêu cầu tiết kiệm và đầu tư mạnh mẽ',
      'Cần chấp nhận rủi ro cao để đạt lợi nhuận cao',
      'Cân nhắc giảm chi tiêu để tăng tốc độ tích lũy',
    ],
    tipsEn: [
      'FIRE requires aggressive saving and investing',
      'Need to accept higher risk for higher returns',
      'Consider reducing expenses to accelerate accumulation',
    ],
  },
  {
    id: 'home-purchase',
    name: 'Mua nhà',
    nameEn: 'Home Purchase',
    description: 'Dành cho người muốn tích lũy để mua nhà trong tương lai.',
    descriptionEn: 'For individuals who want to save to buy a home in the future.',
    icon: 'home',
    category: TemplateCategory.PURCHASE,
    defaults: {
      targetMethod: 'direct',
      targetPresentValue: 3000000000,
      initialInvestment: 200000000,
      periodicPayment: 15000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: 5,
      expectedReturnRate: undefined,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.MODERATE,
    },
    calculateVariable: CalculatedVariableType.RETURN_RATE,
    guidance: 'Template này phù hợp cho người muốn mua nhà trong 5 năm.',
    guidanceEn: 'This template is suitable for individuals who want to buy a home in 5 years.',
    tips: [
      'Thời gian ngắn (5 năm) nên đầu tư cân bằng, không quá rủi ro',
      'Có thể tăng tiền bổ sung hàng tháng để giảm áp lực lợi nhuận',
      'Theo dõi giá nhà để điều chỉnh mục tiêu nếu cần',
    ],
    tipsEn: [
      'Short time horizon (5 years) requires balanced, not too risky investment',
      'Can increase monthly contributions to reduce return rate pressure',
      'Monitor house prices to adjust target if needed',
    ],
  },
  {
    id: 'education-fund',
    name: 'Quỹ giáo dục',
    nameEn: 'Education Fund',
    description: 'Dành cho phụ huynh muốn tích lũy cho con cái đi học đại học hoặc du học.',
    descriptionEn: 'For parents who want to save for their children\'s university or study abroad.',
    icon: 'school',
    category: TemplateCategory.EDUCATION,
    defaults: {
      targetMethod: 'direct',
      targetPresentValue: 2000000000,
      initialInvestment: 100000000,
      periodicPayment: 8000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: undefined,
      expectedReturnRate: 10,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.MODERATE,
    },
    calculateVariable: CalculatedVariableType.YEARS,
    guidance: 'Template này phù hợp cho phụ huynh muốn tích lũy cho con cái.',
    guidanceEn: 'This template is suitable for parents who want to save for their children.',
    tips: [
      'Bắt đầu sớm sẽ giúp giảm áp lực tích lũy',
      'Có thể tăng tiền bổ sung khi thu nhập tăng',
      'Theo dõi chi phí giáo dục để điều chỉnh mục tiêu',
    ],
    tipsEn: [
      'Starting early will reduce accumulation pressure',
      'Can increase contributions when income increases',
      'Monitor education costs to adjust target',
    ],
  },
  {
    id: 'emergency-fund',
    name: 'Quỹ khẩn cấp',
    nameEn: 'Emergency Fund',
    description: 'Dành cho người muốn xây dựng quỹ khẩn cấp để đối phó với các tình huống bất ngờ.',
    descriptionEn: 'For individuals who want to build an emergency fund to handle unexpected situations.',
    icon: 'emergency',
    category: TemplateCategory.EMERGENCY,
    defaults: {
      targetMethod: 'fromExpenses',
      monthlyExpenses: 30000000,
      monthsToSustain: 6,
      targetPresentValue: 180000000,
      initialInvestment: 50000000,
      periodicPayment: 2000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: undefined,
      expectedReturnRate: 6,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.CONSERVATIVE,
    },
    calculateVariable: CalculatedVariableType.YEARS,
    guidance: 'Template này phù hợp cho người muốn xây dựng quỹ khẩn cấp. Quỹ khẩn cấp nên được đầu tư an toàn, thanh khoản cao.',
    guidanceEn: 'This template is suitable for building an emergency fund. Emergency funds should be invested safely with high liquidity.',
    tips: [
      'Quỹ khẩn cấp nên bằng 3-6 tháng chi phí sinh hoạt',
      'Ưu tiên an toàn và thanh khoản hơn lợi nhuận',
      'Không nên đầu tư quỹ khẩn cấp vào tài sản rủi ro cao',
    ],
    tipsEn: [
      'Emergency fund should equal 3-6 months of expenses',
      'Prioritize safety and liquidity over returns',
      'Do not invest emergency fund in high-risk assets',
    ],
  },
  {
    id: 'children-future',
    name: 'Tích lũy cho con cái',
    nameEn: 'Children\'s Future Fund',
    description: 'Dành cho phụ huynh muốn tích lũy dài hạn cho con cái (18-20 năm).',
    descriptionEn: 'For parents who want to save long-term for their children (18-20 years).',
    icon: 'child',
    category: TemplateCategory.EDUCATION,
    defaults: {
      targetMethod: 'direct',
      targetPresentValue: 1000000000,
      initialInvestment: 50000000,
      periodicPayment: 5000000,
      paymentFrequency: PaymentFrequency.MONTHLY,
      paymentType: PaymentType.CONTRIBUTION,
      investmentYears: 12,
      expectedReturnRate: undefined,
      inflationRate: 4.5,
      riskTolerance: RiskTolerance.MODERATE,
    },
    calculateVariable: CalculatedVariableType.RETURN_RATE,
    guidance: 'Template này phù hợp cho phụ huynh muốn tích lũy dài hạn cho con cái. Với thời gian dài (18 năm), có thể đầu tư mạnh hơn.',
    guidanceEn: 'This template is suitable for parents saving long-term for children. With long time horizon (18 years), can invest more aggressively.',
    tips: [
      'Thời gian dài cho phép chấp nhận rủi ro cao hơn',
      'Có thể tăng % cổ phiếu để tối đa hóa lợi nhuận',
      'Bắt đầu sớm sẽ giúp giảm áp lực tích lũy',
    ],
    tipsEn: [
      'Long time horizon allows accepting higher risk',
      'Can increase stock percentage to maximize returns',
      'Starting early will reduce accumulation pressure',
    ],
  },
];

