import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1759981925266 implements MigrationInterface {
    name = 'InitialSchema1759981925266'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."fund_unit_transactions_holding_type_enum" AS ENUM('SUBSCRIBE', 'REDEEM')`);
        await queryRunner.query(`CREATE TABLE "fund_unit_transactions" ("transaction_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "holding_id" uuid NOT NULL, "cash_flow_id" uuid, "holding_type" "public"."fund_unit_transactions_holding_type_enum" NOT NULL, "units" numeric(20,3) NOT NULL, "nav_per_unit" numeric(20,3) NOT NULL, "amount" numeric(20,3) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96a0fc863bae222d87f434080f3" PRIMARY KEY ("transaction_id"))`);
        await queryRunner.query(`CREATE TABLE "investor_holdings" ("holding_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "portfolio_id" uuid NOT NULL, "total_units" numeric(20,3) NOT NULL DEFAULT '0', "avg_cost_per_unit" numeric(20,3) NOT NULL DEFAULT '0', "total_investment" numeric(20,3) NOT NULL DEFAULT '0', "current_value" numeric(20,3) NOT NULL DEFAULT '0', "unrealized_pnl" numeric(20,3) NOT NULL DEFAULT '0', "realized_pnl" numeric(20,3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3af052a79fb99815bf23ad37ef2" UNIQUE ("account_id", "portfolio_id"), CONSTRAINT "PK_cd7fcfdb9940018666f348d1508" PRIMARY KEY ("holding_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4dbc4910fe5139ceccf8650f4" ON "investor_holdings" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2289f5adffb45d036ff198c6ff" ON "investor_holdings" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e61758a3e6fe56b51c014f73c" ON "investor_holdings" ("account_id") `);
        await queryRunner.query(`CREATE TABLE "accounts" ("account_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "base_currency" character varying(3) NOT NULL DEFAULT 'VND', "is_investor" boolean NOT NULL DEFAULT false, "is_main_account" boolean NOT NULL DEFAULT false, "is_demo_account" boolean NOT NULL DEFAULT false, "user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ee66de6cdc53993296d1ceb8aa0" UNIQUE ("email"), CONSTRAINT "PK_abcd260aa34b3ad2c0ff663dc20" PRIMARY KEY ("account_id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_accounts_is_demo_account" ON "accounts" ("is_demo_account")`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_accounts_user_id" ON "accounts" ("user_id")`);
        await queryRunner.query(`CREATE TABLE "nav_snapshots" ("portfolioId" uuid NOT NULL, "nav_date" date NOT NULL, "nav_value" numeric(15,2) NOT NULL, "cash_balance" numeric(15,2) NOT NULL, "total_value" numeric(15,2) NOT NULL, "total_outstanding_units" numeric(20,3) NOT NULL DEFAULT '0', "nav_per_unit" numeric(20,3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f0349d9f6ccc489dae03b64583" PRIMARY KEY ("portfolioId", "nav_date"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe75668f01a2a3d56d9214c22d" ON "nav_snapshots" ("nav_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f0349d9f6ccc489dae03b6458" ON "nav_snapshots" ("portfolioId", "nav_date") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_flows_type_enum" AS ENUM('DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE', 'TAX', 'ADJUSTMENT', 'BUY_TRADE', 'SELL_TRADE', 'DEPOSIT_CREATION', 'DEPOSIT_SETTLEMENT', 'OTHER', 'TRADE_SETTLEMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."cash_flows_status_enum" AS ENUM('PENDING', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "cash_flows" ("cash_flow_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "type" "public"."cash_flows_type_enum" NOT NULL, "amount" numeric(20,8) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'VND', "description" text, "reference" character varying(50), "status" "public"."cash_flows_status_enum" NOT NULL DEFAULT 'COMPLETED', "flow_date" TIMESTAMP NOT NULL, "effective_date" TIMESTAMP, "trade_id" uuid, "funding_source" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99316666a04c92e5e713bed297f" PRIMARY KEY ("cash_flow_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c165ff5f104938591c31d6aa72" ON "cash_flows" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e111dca732e710c55205e9422c" ON "cash_flows" ("flow_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e33a679a64c347f651312bdb1" ON "cash_flows" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "deposits" ("deposit_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "bank_name" character varying(100) NOT NULL, "account_number" character varying(50), "principal" numeric(20,2) NOT NULL, "interest_rate" numeric(5,2) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "term_months" integer, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "actual_interest" numeric(20,2), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "settled_at" TIMESTAMP, CONSTRAINT "PK_ae490d8b3f198a0597b74a0465d" PRIMARY KEY ("deposit_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d917696992440ad0c618862683" ON "deposits" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ced8c21c144697eeec3feea42" ON "deposits" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1360099bd018167c768e9cb441" ON "deposits" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2a820b001b9cfe95666365680" ON "deposits" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "portfolios" ("portfolio_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "base_currency" character varying(3) NOT NULL DEFAULT 'VND', "funding_source" character varying(100), "total_value" numeric(15,2) NOT NULL DEFAULT '0', "cash_balance" numeric(15,2) NOT NULL DEFAULT '0', "unrealized_pl" numeric(15,2) NOT NULL DEFAULT '0', "realized_pl" numeric(15,2) NOT NULL DEFAULT '0', "total_asset_value" numeric(15,2) NOT NULL DEFAULT '0', "total_invest_value" numeric(15,2) NOT NULL DEFAULT '0', "total_all_value" numeric(15,2) NOT NULL DEFAULT '0', "realized_asset_pnl" numeric(15,2) NOT NULL DEFAULT '0', "realized_invest_pnl" numeric(15,2) NOT NULL DEFAULT '0', "realized_all_pnl" numeric(15,2) NOT NULL DEFAULT '0', "unrealized_asset_pnl" numeric(15,2) NOT NULL DEFAULT '0', "unrealized_invest_pnl" numeric(15,2) NOT NULL DEFAULT '0', "unrealized_all_pnl" numeric(15,2) NOT NULL DEFAULT '0', "is_fund" boolean NOT NULL DEFAULT false, "total_outstanding_units" numeric(20,3) NOT NULL DEFAULT '0', "nav_per_unit" numeric(20,3) NOT NULL DEFAULT '0', "number_of_investors" integer NOT NULL DEFAULT '0', "last_nav_date" TIMESTAMP, "visibility" character varying(20) NOT NULL DEFAULT 'PRIVATE', "template_name" character varying(100), "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9303b853b1d0672da696dc70a10" PRIMARY KEY ("portfolio_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfdc33481d4a493b4f445a6a26" ON "portfolios" ("account_id") `);
        await queryRunner.query(`CREATE TYPE "public"."assets_type_enum" AS ENUM('STOCK', 'BOND', 'GOLD', 'CRYPTO', 'COMMODITY', 'DEPOSIT', 'CASH')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "symbol" character varying(50) NOT NULL, "type" "public"."assets_type_enum" NOT NULL DEFAULT 'STOCK', "description" text, "initial_value" numeric(15,2), "initial_quantity" numeric(15,4), "current_quantity" numeric(15,4), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid NOT NULL, "updated_by" uuid NOT NULL, CONSTRAINT "UQ_ASSET_USER_SYMBOL" UNIQUE ("created_by", "symbol"), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_CREATED_BY" ON "assets" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_USER_NAME" ON "assets" ("created_by", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_SYMBOL" ON "assets" ("symbol") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_TYPE" ON "assets" ("type") `);
        await queryRunner.query(`CREATE TABLE "trade_details" ("detail_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sell_trade_id" uuid NOT NULL, "buy_trade_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "matched_qty" numeric(18,8) NOT NULL, "buy_price" numeric(18,8) NOT NULL, "sell_price" numeric(18,8) NOT NULL, "fee_tax" numeric(18,8) NOT NULL DEFAULT '0', "pnl" numeric(18,8) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8c10f058ba49660d0ae9ff6a83" PRIMARY KEY ("detail_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ee6b8fecc23ad130ba7efebd0" ON "trade_details" ("asset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f9e779187758f66864910d56d" ON "trade_details" ("buy_trade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a303e57b225f6438d8c353778" ON "trade_details" ("sell_trade_id") `);
        await queryRunner.query(`CREATE TYPE "public"."trades_side_enum" AS ENUM('BUY', 'SELL', 'BONUS')`);
        await queryRunner.query(`CREATE TYPE "public"."trades_trade_type_enum" AS ENUM('NORMAL', 'MARKET', 'LIMIT', 'STOP', 'CANCEL', 'OPTION')`);
        await queryRunner.query(`CREATE TABLE "trades" ("trade_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "trade_date" TIMESTAMP NOT NULL, "side" "public"."trades_side_enum" NOT NULL, "quantity" numeric(18,8) NOT NULL, "price" numeric(18,8) NOT NULL, "fee" numeric(18,8) NOT NULL DEFAULT '0', "tax" numeric(18,8) NOT NULL DEFAULT '0', "trade_type" "public"."trades_trade_type_enum" NOT NULL DEFAULT 'NORMAL', "source" character varying(100), "exchange" character varying(100), "funding_source" character varying(100), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c21f7caf3ffad61ea326d72853" PRIMARY KEY ("trade_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_230238793873f9cbf197624829" ON "trades" ("side") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce72eb2d12d5ad37d25ec1d5f0" ON "trades" ("trade_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1628a75c483742377ebcf53f53" ON "trades" ("asset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a46262bf5530d16b2722935d1" ON "trades" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "asset_targets" ("asset_id" uuid NOT NULL, "stopLoss" numeric(18,8), "takeProfit" numeric(18,8), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_89e1e884480ed2010047509c862" PRIMARY KEY ("asset_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."portfolio_snapshots_granularity_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "portfolio_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "portfolio_name" character varying(255) NOT NULL, "snapshot_date" date NOT NULL, "granularity" "public"."portfolio_snapshots_granularity_enum" NOT NULL DEFAULT 'DAILY', "total_asset_value" numeric(20,8) NOT NULL DEFAULT '0', "total_asset_invested" numeric(20,8) NOT NULL DEFAULT '0', "total_asset_pl" numeric(20,8) NOT NULL DEFAULT '0', "unrealized_asset_pl" numeric(20,8) NOT NULL DEFAULT '0', "realized_asset_pl" numeric(20,8) NOT NULL DEFAULT '0', "total_portfolio_pl" numeric(20,8) NOT NULL DEFAULT '0', "unrealized_portfolio_pl" numeric(20,8) NOT NULL DEFAULT '0', "realized_portfolio_pl" numeric(20,8) NOT NULL DEFAULT '0', "total_return" numeric(15,6) NOT NULL DEFAULT '0', "cash_balance" numeric(20,8) NOT NULL DEFAULT '0', "total_portfolio_value" numeric(20,8) NOT NULL DEFAULT '0', "total_portfolio_invested" numeric(20,8) NOT NULL DEFAULT '0', "total_deposit_principal" numeric(20,8) NOT NULL DEFAULT '0', "total_deposit_interest" numeric(20,8) NOT NULL DEFAULT '0', "total_deposit_value" numeric(20,8) NOT NULL DEFAULT '0', "total_deposit_count" integer NOT NULL DEFAULT '0', "total_outstanding_units" numeric(20,8) NOT NULL DEFAULT '0', "nav_per_unit" numeric(20,8) NOT NULL DEFAULT '0', "number_of_investors" integer NOT NULL DEFAULT '0', "is_fund" boolean NOT NULL DEFAULT false, "unrealized_deposit_pnl" numeric(20,8) NOT NULL DEFAULT '0', "realized_deposit_pnl" numeric(20,8) NOT NULL DEFAULT '0', "asset_daily_return" numeric(15,6) NOT NULL DEFAULT '0', "asset_weekly_return" numeric(15,6) NOT NULL DEFAULT '0', "asset_monthly_return" numeric(15,6) NOT NULL DEFAULT '0', "asset_ytd_return" numeric(15,6) NOT NULL DEFAULT '0', "asset_volatility" numeric(15,6) NOT NULL DEFAULT '0', "asset_max_drawdown" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_daily_return" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_weekly_return" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_monthly_return" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_ytd_return" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_volatility" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_max_drawdown" numeric(15,6) NOT NULL DEFAULT '0', "daily_return" numeric(15,6) NOT NULL DEFAULT '0', "weekly_return" numeric(15,6) NOT NULL DEFAULT '0', "monthly_return" numeric(15,6) NOT NULL DEFAULT '0', "ytd_return" numeric(15,6) NOT NULL DEFAULT '0', "volatility" numeric(15,6) NOT NULL DEFAULT '0', "max_drawdown" numeric(15,6) NOT NULL DEFAULT '0', "asset_allocation" jsonb, "asset_count" integer NOT NULL DEFAULT '0', "active_asset_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying(100), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_46c13ef40300b3a6d379488f53a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1229c389ede40e88d5d4353f16" ON "portfolio_snapshots" ("portfolio_id", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccb34b122466ac7ef1b9d364c4" ON "portfolio_snapshots" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_96adc2573ddeea709c2dcaeb52" ON "portfolio_snapshots" ("portfolio_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TYPE "public"."portfolio_performance_snapshots_granularity_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "portfolio_performance_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "snapshot_date" date NOT NULL, "granularity" "public"."portfolio_performance_snapshots_granularity_enum" NOT NULL DEFAULT 'DAILY', "portfolio_twr_1d" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_1w" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_6m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_twr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_mwr_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_mwr_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_mwr_6m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_mwr_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_mwr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_irr_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_irr_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_irr_6m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_irr_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_irr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_alpha_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_alpha_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_alpha_6m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_alpha_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_alpha_ytd" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_beta_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_beta_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_beta_6m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_beta_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_beta_ytd" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_information_ratio_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_information_ratio_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_information_ratio_1y" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_tracking_error_1m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_tracking_error_3m" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_tracking_error_1y" numeric(15,6) NOT NULL DEFAULT '0', "total_cash_inflows" numeric(20,8) NOT NULL DEFAULT '0', "total_cash_outflows" numeric(20,8) NOT NULL DEFAULT '0', "net_cash_flow" numeric(20,8) NOT NULL DEFAULT '0', "benchmark_data" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7209b69a58427ac6246533b90fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_888fb5b8b401d0198dc25304bb" ON "portfolio_performance_snapshots" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_2182a03f095194bc57987b4065" ON "portfolio_performance_snapshots" ("portfolio_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TABLE "benchmark_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "benchmark_id" uuid NOT NULL, "benchmark_name" character varying(255) NOT NULL, "benchmark_type" character varying(50) NOT NULL, "snapshot_date" date NOT NULL, "granularity" character varying(20) NOT NULL DEFAULT 'DAILY', "benchmark_value" numeric(20,8) NOT NULL DEFAULT '0', "benchmark_return_1d" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_1w" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_1m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_3m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_6m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_1y" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_return_ytd" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_volatility_1m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_volatility_3m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_volatility_1y" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_max_drawdown_1m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_max_drawdown_3m" numeric(15,6) NOT NULL DEFAULT '0', "benchmark_max_drawdown_1y" numeric(15,6) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a9094f02ae84cdc8b02646ff6af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75b9a5fc318f1ac4bb7f9f3d42" ON "benchmark_data" ("benchmark_type", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca4a10faf893d2165896f0bdd4" ON "benchmark_data" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_cddae9e094db8d7d3919a62297" ON "benchmark_data" ("benchmark_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TYPE "public"."asset_performance_snapshots_granularity_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "asset_performance_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "asset_symbol" character varying(50) NOT NULL, "snapshot_date" date NOT NULL, "granularity" "public"."asset_performance_snapshots_granularity_enum" NOT NULL DEFAULT 'DAILY', "asset_twr_1d" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_1w" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_6m" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_twr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "asset_volatility_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_volatility_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_volatility_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_sharpe_ratio_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_sharpe_ratio_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_sharpe_ratio_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_max_drawdown_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_max_drawdown_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_max_drawdown_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_risk_adjusted_return_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_risk_adjusted_return_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_risk_adjusted_return_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_irr_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_irr_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_irr_6m" numeric(15,6) NOT NULL DEFAULT '0', "asset_irr_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_irr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "asset_alpha_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_alpha_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_alpha_6m" numeric(15,6) NOT NULL DEFAULT '0', "asset_alpha_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_alpha_ytd" numeric(15,6) NOT NULL DEFAULT '0', "asset_beta_1m" numeric(15,6) NOT NULL DEFAULT '0', "asset_beta_3m" numeric(15,6) NOT NULL DEFAULT '0', "asset_beta_6m" numeric(15,6) NOT NULL DEFAULT '0', "asset_beta_1y" numeric(15,6) NOT NULL DEFAULT '0', "asset_beta_ytd" numeric(15,6) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84948841dcf87e19f04d532d495" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b97a5820fb1902432d568cdce" ON "asset_performance_snapshots" ("asset_symbol", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5d324506b708ade94b9ff7965" ON "asset_performance_snapshots" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe206d5178d30f8c65616c55a5" ON "asset_performance_snapshots" ("portfolio_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b4644351f5ba0da1450a05e9" ON "asset_performance_snapshots" ("portfolio_id", "asset_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TYPE "public"."asset_group_performance_snapshots_granularity_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "asset_group_performance_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "asset_type" character varying(50) NOT NULL, "snapshot_date" date NOT NULL, "granularity" "public"."asset_group_performance_snapshots_granularity_enum" NOT NULL DEFAULT 'DAILY', "group_twr_1d" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_1w" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_6m" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_twr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "group_sharpe_ratio_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_sharpe_ratio_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_sharpe_ratio_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_volatility_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_volatility_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_volatility_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_max_drawdown_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_max_drawdown_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_max_drawdown_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_risk_adjusted_return_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_risk_adjusted_return_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_risk_adjusted_return_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_irr_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_irr_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_irr_6m" numeric(15,6) NOT NULL DEFAULT '0', "group_irr_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_irr_ytd" numeric(15,6) NOT NULL DEFAULT '0', "group_alpha_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_alpha_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_alpha_6m" numeric(15,6) NOT NULL DEFAULT '0', "group_alpha_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_alpha_ytd" numeric(15,6) NOT NULL DEFAULT '0', "group_beta_1m" numeric(15,6) NOT NULL DEFAULT '0', "group_beta_3m" numeric(15,6) NOT NULL DEFAULT '0', "group_beta_6m" numeric(15,6) NOT NULL DEFAULT '0', "group_beta_1y" numeric(15,6) NOT NULL DEFAULT '0', "group_beta_ytd" numeric(15,6) NOT NULL DEFAULT '0', "asset_count" integer NOT NULL DEFAULT '0', "active_asset_count" integer NOT NULL DEFAULT '0', "allocation_percentage" numeric(15,6) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6728c33a7af6b2a9f1959e9531c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a4fca0b46febccf67dfcc526c" ON "asset_group_performance_snapshots" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_56f6ff6701449e44146ffd4ead" ON "asset_group_performance_snapshots" ("portfolio_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb5d3993199af742704e48cd58" ON "asset_group_performance_snapshots" ("portfolio_id", "asset_type", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TYPE "public"."asset_allocation_snapshots_granularity_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "asset_allocation_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolio_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "asset_symbol" character varying(50) NOT NULL, "asset_type" character varying(50) NOT NULL, "snapshot_date" date NOT NULL, "granularity" "public"."asset_allocation_snapshots_granularity_enum" NOT NULL DEFAULT 'DAILY', "quantity" numeric(20,8) NOT NULL DEFAULT '0', "current_price" numeric(20,8) NOT NULL DEFAULT '0', "current_value" numeric(20,8) NOT NULL DEFAULT '0', "cost_basis" numeric(20,8) NOT NULL DEFAULT '0', "avg_cost" numeric(20,8) NOT NULL DEFAULT '0', "realized_pl" numeric(20,8) NOT NULL DEFAULT '0', "unrealized_pl" numeric(20,8) NOT NULL DEFAULT '0', "total_pl" numeric(20,8) NOT NULL DEFAULT '0', "allocation_percentage" numeric(15,6) NOT NULL DEFAULT '0', "portfolio_total_value" numeric(20,8) NOT NULL DEFAULT '0', "return_percentage" numeric(15,6) NOT NULL DEFAULT '0', "daily_return" numeric(15,6) NOT NULL DEFAULT '0', "cumulative_return" numeric(15,6) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying(100), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4843e41cf8478f69ff7885b4b5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eff054d55b8821bcab2ba47c6f" ON "asset_allocation_snapshots" ("asset_symbol", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e16d5b50fa78fb13ee6a0eff3d" ON "asset_allocation_snapshots" ("snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE INDEX "IDX_60f73b0391f07be52472e7fe79" ON "asset_allocation_snapshots" ("portfolio_id", "asset_id", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f176e48b57481f0590c7db94c" ON "asset_allocation_snapshots" ("portfolio_id", "snapshot_date", "granularity") `);
        await queryRunner.query(`CREATE TABLE "request_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "method" character varying(10) NOT NULL, "url" text NOT NULL, "headers" jsonb, "body" jsonb, "query_params" jsonb, "user_id" uuid, "ip_address" inet, "user_agent" text, "response_status" integer, "response_time_ms" integer, "response_size_bytes" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c3473f89532dbd640696cf61ed9" UNIQUE ("request_id"), CONSTRAINT "UQ_request_logs_request_id" UNIQUE ("request_id"), CONSTRAINT "PK_1edd3815ae37a9b9511f5a26dca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_req_logs_url" ON "request_logs" ("url") `);
        await queryRunner.query(`CREATE INDEX "idx_req_logs_method" ON "request_logs" ("method") `);
        await queryRunner.query(`CREATE INDEX "idx_req_logs_response_status" ON "request_logs" ("response_status") `);
        await queryRunner.query(`CREATE INDEX "idx_req_logs_user_id" ON "request_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_req_logs_timestamp" ON "request_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "performance_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "operation_name" character varying(100) NOT NULL, "operation_type" character varying(50) NOT NULL, "duration_ms" integer NOT NULL, "memory_usage_mb" numeric(10,2), "cpu_usage_percent" numeric(5,2), "database_queries" integer, "cache_hits" integer, "cache_misses" integer, "external_api_calls" integer, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75fdbcc18d181201a23de58f130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_perf_logs_operation_type" ON "performance_logs" ("operation_type") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_logs_duration_ms" ON "performance_logs" ("duration_ms") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_logs_operation_name" ON "performance_logs" ("operation_name") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_logs_timestamp" ON "performance_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "business_event_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" uuid NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event_type" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "user_id" uuid, "action" character varying(50) NOT NULL, "old_values" jsonb, "new_values" jsonb, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "portfolio_id" uuid, "trade_id" uuid, CONSTRAINT "UQ_f12c43f255edf49b0b61eadbef3" UNIQUE ("event_id"), CONSTRAINT "UQ_business_event_logs_event_id" UNIQUE ("event_id"), CONSTRAINT "PK_9d2924da8ef4506448ba4ef8fce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_biz_logs_action" ON "business_event_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_biz_logs_user_id" ON "business_event_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_biz_logs_entity_type" ON "business_event_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "idx_biz_logs_event_type" ON "business_event_logs" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_biz_logs_timestamp" ON "business_event_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "application_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "level" character varying(20) NOT NULL, "message" text NOT NULL, "context" jsonb, "request_id" uuid, "user_id" uuid, "service_name" character varying(100) NOT NULL, "module_name" character varying(100), "function_name" character varying(100), "error_code" character varying(50), "stack_trace" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "portfolio_id" uuid, "trade_id" uuid, CONSTRAINT "PK_ffc2b5aecb856403c56de243529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_context" ON "application_logs" ("context") `);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_service" ON "application_logs" ("service_name") `);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_user_id" ON "application_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_request_id" ON "application_logs" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_level" ON "application_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "idx_app_logs_timestamp" ON "application_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "asset_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asset_id" uuid NOT NULL, "current_price" numeric(15,2) NOT NULL, "price_type" character varying(20) NOT NULL DEFAULT 'MANUAL', "price_source" character varying(30) NOT NULL DEFAULT 'USER', "last_price_update" TIMESTAMP NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ASSET_PRICE_ASSET_ID" UNIQUE ("asset_id"), CONSTRAINT "REL_5fa729bf053c3810d2a0bbad00" UNIQUE ("asset_id"), CONSTRAINT "CHK_ASSET_PRICE_SOURCE_VALID" CHECK (price_source IN ('USER_INPUT', 'EXTERNAL_API')), CONSTRAINT "CHK_ASSET_PRICE_TYPE_VALID" CHECK (price_type IN ('MANUAL', 'EXTERNAL')), CONSTRAINT "CHK_ASSET_PRICE_POSITIVE" CHECK (current_price > 0), CONSTRAINT "PK_86982518bff41e3f51974a444cd" PRIMARY KEY ("id")); COMMENT ON COLUMN "asset_prices"."asset_id" IS 'Foreign key to global_assets table'; COMMENT ON COLUMN "asset_prices"."current_price" IS 'Current price of the asset'; COMMENT ON COLUMN "asset_prices"."price_type" IS 'Type of the price'; COMMENT ON COLUMN "asset_prices"."price_source" IS 'Source of the price'; COMMENT ON COLUMN "asset_prices"."last_price_update" IS 'Timestamp when price was last updated'; COMMENT ON COLUMN "asset_prices"."metadata" IS 'Optional metadata about the price'; COMMENT ON COLUMN "asset_prices"."created_at" IS 'Price record creation timestamp'; COMMENT ON COLUMN "asset_prices"."updated_at" IS 'Price record last update timestamp'`);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_UPDATE" ON "asset_prices" ("last_price_update") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_SOURCE" ON "asset_prices" ("price_source") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_TYPE" ON "asset_prices" ("price_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_ASSET_ID" ON "asset_prices" ("asset_id") `);
        await queryRunner.query(`CREATE TABLE "asset_price_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asset_id" uuid NOT NULL, "price" numeric(15,2) NOT NULL, "price_type" character varying(20) NOT NULL DEFAULT 'MANUAL', "price_source" character varying(30) NOT NULL DEFAULT 'USER', "change_reason" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL, CONSTRAINT "CHK_ASSET_PRICE_HISTORY_SOURCE_VALID" CHECK (price_source IN ('USER_INPUT', 'EXTERNAL_API')), CONSTRAINT "CHK_ASSET_PRICE_HISTORY_TYPE_VALID" CHECK (price_type IN ('MANUAL', 'EXTERNAL')), CONSTRAINT "CHK_ASSET_PRICE_HISTORY_POSITIVE" CHECK (price > 0), CONSTRAINT "PK_26d98c4a4679bbe91a268302cd7" PRIMARY KEY ("id")); COMMENT ON COLUMN "asset_price_history"."created_at" IS 'Price history record creation timestamp'`);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_HISTORY_PRICE_SOURCE" ON "asset_price_history" ("price_source") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_HISTORY_PRICE_TYPE" ON "asset_price_history" ("price_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_HISTORY_CREATED_AT" ON "asset_price_history" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSET_PRICE_HISTORY_ASSET_ID" ON "asset_price_history" ("asset_id") `);
        await queryRunner.query(`CREATE TYPE "public"."global_assets_type_enum" AS ENUM('STOCK', 'BOND', 'GOLD', 'CRYPTO', 'COMMODITY', 'DEPOSIT', 'CASH')`);
        await queryRunner.query(`CREATE TABLE "global_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "symbol" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."global_assets_type_enum" NOT NULL DEFAULT 'STOCK', "nation" character varying(2) NOT NULL, "market_code" character varying(20) NOT NULL, "currency" character varying(3) NOT NULL, "timezone" character varying(50) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_GLOBAL_ASSET_SYMBOL_NATION" UNIQUE ("symbol", "nation"), CONSTRAINT "CHK_GLOBAL_ASSET_TIMEZONE_FORMAT" CHECK (timezone ~ '^[A-Za-z_/]+$'), CONSTRAINT "CHK_GLOBAL_ASSET_CURRENCY_FORMAT" CHECK (currency ~ '^[A-Z]{3}$'), CONSTRAINT "CHK_GLOBAL_ASSET_MARKET_CODE_FORMAT" CHECK (market_code ~ '^[A-Z0-9-]+$'), CONSTRAINT "CHK_GLOBAL_ASSET_NATION_FORMAT" CHECK (nation ~ '^[A-Z]{2}$'), CONSTRAINT "CHK_GLOBAL_ASSET_SYMBOL_FORMAT" CHECK (symbol ~ '^[A-Z0-9-]+$'), CONSTRAINT "PK_88f08f8eb972f5ef716eb2cd4f3" PRIMARY KEY ("id")); COMMENT ON COLUMN "global_assets"."symbol" IS 'Asset symbol for trading - uppercase alphanumeric with dashes'; COMMENT ON COLUMN "global_assets"."name" IS 'Asset name'; COMMENT ON COLUMN "global_assets"."type" IS 'Asset type'; COMMENT ON COLUMN "global_assets"."nation" IS 'Nation code - 2-letter ISO country code'; COMMENT ON COLUMN "global_assets"."market_code" IS 'Market code where asset is traded'; COMMENT ON COLUMN "global_assets"."currency" IS 'Currency code - 3-letter ISO currency code'; COMMENT ON COLUMN "global_assets"."timezone" IS 'Timezone for asset market'; COMMENT ON COLUMN "global_assets"."is_active" IS 'Asset active status'; COMMENT ON COLUMN "global_assets"."description" IS 'Asset description'; COMMENT ON COLUMN "global_assets"."created_at" IS 'Asset creation timestamp'; COMMENT ON COLUMN "global_assets"."updated_at" IS 'Asset last update timestamp'`);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_ASSET_SYMBOL_NATION" ON "global_assets" ("symbol", "nation") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_ASSET_ACTIVE" ON "global_assets" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_ASSET_TYPE" ON "global_assets" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_ASSET_NATION" ON "global_assets" ("nation") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_ASSET_SYMBOL" ON "global_assets" ("symbol") `);
        await queryRunner.query(`ALTER TABLE "fund_unit_transactions" ADD CONSTRAINT "FK_875d8b4642f6a99ee322b782d8a" FOREIGN KEY ("holding_id") REFERENCES "investor_holdings"("holding_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investor_holdings" ADD CONSTRAINT "FK_9e61758a3e6fe56b51c014f73c9" FOREIGN KEY ("account_id") REFERENCES "accounts"("account_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investor_holdings" ADD CONSTRAINT "FK_2289f5adffb45d036ff198c6ff9" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" ADD CONSTRAINT "FK_215047c4208599b6b12fe9a1236" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_flows" ADD CONSTRAINT "FK_6e33a679a64c347f651312bdb1e" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_b2a820b001b9cfe95666365680d" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d" FOREIGN KEY ("account_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_8a303e57b225f6438d8c353778f" FOREIGN KEY ("sell_trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_5f9e779187758f66864910d56d6" FOREIGN KEY ("buy_trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_9ee6b8fecc23ad130ba7efebd07" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_2a46262bf5530d16b2722935d15" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_1628a75c483742377ebcf53f539" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_targets" ADD CONSTRAINT "FK_89e1e884480ed2010047509c862" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_snapshots" ADD CONSTRAINT "FK_de294421d3b9ba2ba8dc665badd" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_performance_snapshots" ADD CONSTRAINT "FK_40e19599b73bfaa6da0ea012232" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_performance_snapshots" ADD CONSTRAINT "FK_ff3bf594a89251aceaea83c5511" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_performance_snapshots" ADD CONSTRAINT "FK_2f394d60d3cc6f8b30d0c0f7001" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_group_performance_snapshots" ADD CONSTRAINT "FK_0ae3b464828263f4192c54187ba" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_allocation_snapshots" ADD CONSTRAINT "FK_09fbbb16159f8b017ed2bcb666f" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_allocation_snapshots" ADD CONSTRAINT "FK_55cb458b6c7f5d471b375b03c7e" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_logs" ADD CONSTRAINT "FK_b5f9dbba1a152b519ef219b94e1" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_dfed99ad3b558b35bd5dedd8136" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_a26fd22a89d3e91de2e18b22cd4" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_9db960ef7b9040a73a775047f9b" FOREIGN KEY ("trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_73d7020c15d8b2f0f7833dcb2a1" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_deb5748e93586a2d11fd4c41a17" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_5f09d9e345af4c5777c7d252857" FOREIGN KEY ("trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_prices" ADD CONSTRAINT "FK_5fa729bf053c3810d2a0bbad00d" FOREIGN KEY ("asset_id") REFERENCES "global_assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_price_history" ADD CONSTRAINT "FK_e070cfd7bb86654c8c2d07a3337" FOREIGN KEY ("asset_id") REFERENCES "global_assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_price_history" DROP CONSTRAINT "FK_e070cfd7bb86654c8c2d07a3337"`);
        await queryRunner.query(`ALTER TABLE "asset_prices" DROP CONSTRAINT "FK_5fa729bf053c3810d2a0bbad00d"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_5f09d9e345af4c5777c7d252857"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_deb5748e93586a2d11fd4c41a17"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_73d7020c15d8b2f0f7833dcb2a1"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_9db960ef7b9040a73a775047f9b"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_a26fd22a89d3e91de2e18b22cd4"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_dfed99ad3b558b35bd5dedd8136"`);
        await queryRunner.query(`ALTER TABLE "request_logs" DROP CONSTRAINT "FK_b5f9dbba1a152b519ef219b94e1"`);
        await queryRunner.query(`ALTER TABLE "asset_allocation_snapshots" DROP CONSTRAINT "FK_55cb458b6c7f5d471b375b03c7e"`);
        await queryRunner.query(`ALTER TABLE "asset_allocation_snapshots" DROP CONSTRAINT "FK_09fbbb16159f8b017ed2bcb666f"`);
        await queryRunner.query(`ALTER TABLE "asset_group_performance_snapshots" DROP CONSTRAINT "FK_0ae3b464828263f4192c54187ba"`);
        await queryRunner.query(`ALTER TABLE "asset_performance_snapshots" DROP CONSTRAINT "FK_2f394d60d3cc6f8b30d0c0f7001"`);
        await queryRunner.query(`ALTER TABLE "asset_performance_snapshots" DROP CONSTRAINT "FK_ff3bf594a89251aceaea83c5511"`);
        await queryRunner.query(`ALTER TABLE "portfolio_performance_snapshots" DROP CONSTRAINT "FK_40e19599b73bfaa6da0ea012232"`);
        await queryRunner.query(`ALTER TABLE "portfolio_snapshots" DROP CONSTRAINT "FK_de294421d3b9ba2ba8dc665badd"`);
        await queryRunner.query(`ALTER TABLE "asset_targets" DROP CONSTRAINT "FK_89e1e884480ed2010047509c862"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_1628a75c483742377ebcf53f539"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_2a46262bf5530d16b2722935d15"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_9ee6b8fecc23ad130ba7efebd07"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_5f9e779187758f66864910d56d6"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_8a303e57b225f6438d8c353778f"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_b2a820b001b9cfe95666365680d"`);
        await queryRunner.query(`ALTER TABLE "cash_flows" DROP CONSTRAINT "FK_6e33a679a64c347f651312bdb1e"`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" DROP CONSTRAINT "FK_215047c4208599b6b12fe9a1236"`);
        await queryRunner.query(`ALTER TABLE "investor_holdings" DROP CONSTRAINT "FK_2289f5adffb45d036ff198c6ff9"`);
        await queryRunner.query(`ALTER TABLE "investor_holdings" DROP CONSTRAINT "FK_9e61758a3e6fe56b51c014f73c9"`);
        await queryRunner.query(`ALTER TABLE "fund_unit_transactions" DROP CONSTRAINT "FK_875d8b4642f6a99ee322b782d8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GLOBAL_ASSET_SYMBOL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GLOBAL_ASSET_NATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GLOBAL_ASSET_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GLOBAL_ASSET_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GLOBAL_ASSET_SYMBOL_NATION"`);
        await queryRunner.query(`DROP TABLE "global_assets"`);
        await queryRunner.query(`DROP TYPE "public"."global_assets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_HISTORY_ASSET_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_HISTORY_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_HISTORY_PRICE_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_HISTORY_PRICE_SOURCE"`);
        await queryRunner.query(`DROP TABLE "asset_price_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_ASSET_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_SOURCE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_PRICE_UPDATE"`);
        await queryRunner.query(`DROP TABLE "asset_prices"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_logs_context"`);
        await queryRunner.query(`DROP TABLE "application_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_biz_logs_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_biz_logs_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_biz_logs_entity_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_biz_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_biz_logs_action"`);
        await queryRunner.query(`DROP TABLE "business_event_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perf_logs_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perf_logs_operation_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perf_logs_duration_ms"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perf_logs_operation_type"`);
        await queryRunner.query(`DROP TABLE "performance_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_req_logs_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_req_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_req_logs_response_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_req_logs_method"`);
        await queryRunner.query(`DROP INDEX "public"."idx_req_logs_url"`);
        await queryRunner.query(`DROP TABLE "request_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f176e48b57481f0590c7db94c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60f73b0391f07be52472e7fe79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e16d5b50fa78fb13ee6a0eff3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eff054d55b8821bcab2ba47c6f"`);
        await queryRunner.query(`DROP TABLE "asset_allocation_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."asset_allocation_snapshots_granularity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb5d3993199af742704e48cd58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56f6ff6701449e44146ffd4ead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a4fca0b46febccf67dfcc526c"`);
        await queryRunner.query(`DROP TABLE "asset_group_performance_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."asset_group_performance_snapshots_granularity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b4644351f5ba0da1450a05e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe206d5178d30f8c65616c55a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5d324506b708ade94b9ff7965"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b97a5820fb1902432d568cdce"`);
        await queryRunner.query(`DROP TABLE "asset_performance_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."asset_performance_snapshots_granularity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cddae9e094db8d7d3919a62297"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca4a10faf893d2165896f0bdd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75b9a5fc318f1ac4bb7f9f3d42"`);
        await queryRunner.query(`DROP TABLE "benchmark_data"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2182a03f095194bc57987b4065"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_888fb5b8b401d0198dc25304bb"`);
        await queryRunner.query(`DROP TABLE "portfolio_performance_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."portfolio_performance_snapshots_granularity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96adc2573ddeea709c2dcaeb52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccb34b122466ac7ef1b9d364c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1229c389ede40e88d5d4353f16"`);
        await queryRunner.query(`DROP TABLE "portfolio_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."portfolio_snapshots_granularity_enum"`);
        await queryRunner.query(`DROP TABLE "asset_targets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a46262bf5530d16b2722935d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1628a75c483742377ebcf53f53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce72eb2d12d5ad37d25ec1d5f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_230238793873f9cbf197624829"`);
        await queryRunner.query(`DROP TABLE "trades"`);
        await queryRunner.query(`DROP TYPE "public"."trades_trade_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trades_side_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a303e57b225f6438d8c353778"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f9e779187758f66864910d56d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ee6b8fecc23ad130ba7efebd0"`);
        await queryRunner.query(`DROP TABLE "trade_details"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_SYMBOL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_USER_NAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSET_CREATED_BY"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfdc33481d4a493b4f445a6a26"`);
        await queryRunner.query(`DROP TABLE "portfolios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2a820b001b9cfe95666365680"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1360099bd018167c768e9cb441"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ced8c21c144697eeec3feea42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d917696992440ad0c618862683"`);
        await queryRunner.query(`DROP TABLE "deposits"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e33a679a64c347f651312bdb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e111dca732e710c55205e9422c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c165ff5f104938591c31d6aa72"`);
        await queryRunner.query(`DROP TABLE "cash_flows"`);
        await queryRunner.query(`DROP TYPE "public"."cash_flows_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cash_flows_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f0349d9f6ccc489dae03b6458"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe75668f01a2a3d56d9214c22d"`);
        await queryRunner.query(`DROP TABLE "nav_snapshots"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e61758a3e6fe56b51c014f73c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2289f5adffb45d036ff198c6ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4dbc4910fe5139ceccf8650f4"`);
        await queryRunner.query(`DROP TABLE "investor_holdings"`);
        await queryRunner.query(`DROP TABLE "fund_unit_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."fund_unit_transactions_holding_type_enum"`);
    }

}
