import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNotesToTrades1757563759554 implements MigrationInterface {
    name = 'AddNotesToTrades1757563759554'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "portfolio_assets" DROP CONSTRAINT "FK_682c37b81c863dc30f54155045a"`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" DROP CONSTRAINT "FK_96e4f24a6ef0f4c4811296c1aae"`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" DROP CONSTRAINT "FK_1c2ac58c931bc14e33354ea305d"`);
        await queryRunner.query(`ALTER TABLE "cash_flows" DROP CONSTRAINT "FK_6e33a679a64c347f651312bdb1e"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_trade_details_sell_trade_id"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_trade_details_buy_trade_id"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_trade_details_asset_id"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_trades_portfolio_id"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_trades_asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset_targets" DROP CONSTRAINT "FK_asset_targets_asset_id"`);
        await queryRunner.query(`ALTER TABLE "request_logs" DROP CONSTRAINT "FK_request_logs_user_id"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_business_event_logs_user_id"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_application_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_portfolio_assets_asset_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nav_snapshots_portfolio_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nav_snapshots_nav_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cash_flows_portfolio_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cash_flows_flow_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_portfolios_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trade_details_sell_trade_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trade_details_buy_trade_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trade_details_asset_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trades_portfolio_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trades_asset_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trades_trade_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trades_side"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD "portfolioId" uuid`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD "trade_id" uuid`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD "portfolioId" uuid`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD "trade_id" uuid`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_flows" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolios" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "side"`);
        await queryRunner.query(`CREATE TYPE "public"."trades_side_enum" AS ENUM('BUY', 'SELL')`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "side" "public"."trades_side_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "trade_type"`);
        await queryRunner.query(`CREATE TYPE "public"."trades_trade_type_enum" AS ENUM('NORMAL', 'MARKET', 'CANCEL', 'OPTION')`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "trade_type" "public"."trades_trade_type_enum" NOT NULL DEFAULT 'NORMAL'`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "performance_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "request_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "application_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_96e4f24a6ef0f4c4811296c1aa" ON "portfolio_assets" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe75668f01a2a3d56d9214c22d" ON "nav_snapshots" ("nav_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5e5d6a88c5651d90e0aa6c572" ON "nav_snapshots" ("portfolioId", "nav_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e111dca732e710c55205e9422c" ON "cash_flows" ("flow_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e33a679a64c347f651312bdb1" ON "cash_flows" ("portfolioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfdc33481d4a493b4f445a6a26" ON "portfolios" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ee6b8fecc23ad130ba7efebd0" ON "trade_details" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f9e779187758f66864910d56d" ON "trade_details" ("buy_trade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a303e57b225f6438d8c353778" ON "trade_details" ("sell_trade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_230238793873f9cbf197624829" ON "trades" ("side") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce72eb2d12d5ad37d25ec1d5f0" ON "trades" ("trade_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1628a75c483742377ebcf53f53" ON "trades" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a46262bf5530d16b2722935d1" ON "trades" ("portfolioId") `);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ADD CONSTRAINT "FK_682c37b81c863dc30f54155045a" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ADD CONSTRAINT "FK_96e4f24a6ef0f4c4811296c1aae" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" ADD CONSTRAINT "FK_1c2ac58c931bc14e33354ea305d" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_flows" ADD CONSTRAINT "FK_6e33a679a64c347f651312bdb1e" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d" FOREIGN KEY ("account_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_8a303e57b225f6438d8c353778f" FOREIGN KEY ("sell_trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_5f9e779187758f66864910d56d6" FOREIGN KEY ("buy_trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_9ee6b8fecc23ad130ba7efebd07" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_2a46262bf5530d16b2722935d15" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_1628a75c483742377ebcf53f539" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_targets" ADD CONSTRAINT "FK_89e1e884480ed2010047509c862" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_logs" ADD CONSTRAINT "FK_b5f9dbba1a152b519ef219b94e1" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_dfed99ad3b558b35bd5dedd8136" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_a26fd22a89d3e91de2e18b22cd4" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_9db960ef7b9040a73a775047f9b" FOREIGN KEY ("trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_73d7020c15d8b2f0f7833dcb2a1" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_deb5748e93586a2d11fd4c41a17" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_5f09d9e345af4c5777c7d252857" FOREIGN KEY ("trade_id") REFERENCES "trades"("trade_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_5f09d9e345af4c5777c7d252857"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_deb5748e93586a2d11fd4c41a17"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP CONSTRAINT "FK_73d7020c15d8b2f0f7833dcb2a1"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_9db960ef7b9040a73a775047f9b"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_a26fd22a89d3e91de2e18b22cd4"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP CONSTRAINT "FK_dfed99ad3b558b35bd5dedd8136"`);
        await queryRunner.query(`ALTER TABLE "request_logs" DROP CONSTRAINT "FK_b5f9dbba1a152b519ef219b94e1"`);
        await queryRunner.query(`ALTER TABLE "asset_targets" DROP CONSTRAINT "FK_89e1e884480ed2010047509c862"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_1628a75c483742377ebcf53f539"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_2a46262bf5530d16b2722935d15"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_9ee6b8fecc23ad130ba7efebd07"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_5f9e779187758f66864910d56d6"`);
        await queryRunner.query(`ALTER TABLE "trade_details" DROP CONSTRAINT "FK_8a303e57b225f6438d8c353778f"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d"`);
        await queryRunner.query(`ALTER TABLE "cash_flows" DROP CONSTRAINT "FK_6e33a679a64c347f651312bdb1e"`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" DROP CONSTRAINT "FK_1c2ac58c931bc14e33354ea305d"`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" DROP CONSTRAINT "FK_96e4f24a6ef0f4c4811296c1aae"`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" DROP CONSTRAINT "FK_682c37b81c863dc30f54155045a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a46262bf5530d16b2722935d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1628a75c483742377ebcf53f53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce72eb2d12d5ad37d25ec1d5f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_230238793873f9cbf197624829"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a303e57b225f6438d8c353778"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f9e779187758f66864910d56d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ee6b8fecc23ad130ba7efebd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfdc33481d4a493b4f445a6a26"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e33a679a64c347f651312bdb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e111dca732e710c55205e9422c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5e5d6a88c5651d90e0aa6c572"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe75668f01a2a3d56d9214c22d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96e4f24a6ef0f4c4811296c1aa"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application_logs" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "request_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "request_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "request_logs" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "performance_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "performance_logs" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "trade_type"`);
        await queryRunner.query(`DROP TYPE "public"."trades_trade_type_enum"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "trade_type" character varying NOT NULL DEFAULT 'NORMAL'`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "side"`);
        await queryRunner.query(`DROP TYPE "public"."trades_side_enum"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "side" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolios" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "portfolios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cash_flows" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP COLUMN "trade_id"`);
        await queryRunner.query(`ALTER TABLE "application_logs" DROP COLUMN "portfolioId"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP COLUMN "trade_id"`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" DROP COLUMN "portfolioId"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`CREATE INDEX "IDX_trades_side" ON "trades" ("side") `);
        await queryRunner.query(`CREATE INDEX "IDX_trades_trade_date" ON "trades" ("trade_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_trades_asset_id" ON "trades" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_trades_portfolio_id" ON "trades" ("portfolioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_trade_details_asset_id" ON "trade_details" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_trade_details_buy_trade_id" ON "trade_details" ("buy_trade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_trade_details_sell_trade_id" ON "trade_details" ("sell_trade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_portfolios_account_id" ON "portfolios" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cash_flows_flow_date" ON "cash_flows" ("flow_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_cash_flows_portfolio_id" ON "cash_flows" ("portfolioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_nav_snapshots_nav_date" ON "nav_snapshots" ("nav_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_nav_snapshots_portfolio_date" ON "nav_snapshots" ("portfolioId", "nav_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_portfolio_assets_asset_id" ON "portfolio_assets" ("assetId") `);
        await queryRunner.query(`ALTER TABLE "application_logs" ADD CONSTRAINT "FK_application_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_event_logs" ADD CONSTRAINT "FK_business_event_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_logs" ADD CONSTRAINT "FK_request_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts"("account_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_targets" ADD CONSTRAINT "FK_asset_targets_asset_id" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_trades_asset_id" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_trades_portfolio_id" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_trade_details_asset_id" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_trade_details_buy_trade_id" FOREIGN KEY ("buy_trade_id") REFERENCES "trades"("trade_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_details" ADD CONSTRAINT "FK_trade_details_sell_trade_id" FOREIGN KEY ("sell_trade_id") REFERENCES "trades"("trade_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_bfdc33481d4a493b4f445a6a26d" FOREIGN KEY ("account_id") REFERENCES "accounts"("account_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_flows" ADD CONSTRAINT "FK_6e33a679a64c347f651312bdb1e" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_snapshots" ADD CONSTRAINT "FK_1c2ac58c931bc14e33354ea305d" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ADD CONSTRAINT "FK_96e4f24a6ef0f4c4811296c1aae" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_assets" ADD CONSTRAINT "FK_682c37b81c863dc30f54155045a" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
