name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (Backend)
      run: npm run lint

    - name: Run Prettier check (Backend)
      run: npm run format:check

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run ESLint (Frontend)
      working-directory: ./frontend
      run: npm run lint

    - name: Run Prettier check (Frontend)
      working-directory: ./frontend
      run: npm run format:check

    - name: Run TypeScript check (Backend)
      run: npm run build

    - name: Run TypeScript check (Frontend)
      working-directory: ./frontend
      run: npm run build

    - name: Check for TODO/FIXME comments
      run: |
        echo "Checking for TODO/FIXME comments..."
        if grep -r "TODO\|FIXME" src/ --exclude-dir=node_modules; then
          echo "⚠️ Found TODO/FIXME comments. Please address them before merging."
          exit 1
        else
          echo "✅ No TODO/FIXME comments found."
        fi

    - name: Check for console.log statements
      run: |
        echo "Checking for console.log statements..."
        if grep -r "console\.log" src/ --exclude-dir=node_modules; then
          echo "⚠️ Found console.log statements. Please remove them before merging."
          exit 1
        else
          echo "✅ No console.log statements found."
        fi

    - name: Check for unused imports
      run: |
        echo "Checking for unused imports..."
        # This would typically use a tool like ts-unused-exports
        # For now, we'll just check if the build succeeds
        echo "✅ Build check completed."

    - name: Generate code quality report
      run: |
        echo "## Code Quality Report" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ ESLint checks passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Prettier formatting check passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ TypeScript compilation successful" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ No TODO/FIXME comments found" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ No console.log statements found" >> $GITHUB_STEP_SUMMARY
